### ISSUE TITLE
Great idea, bad file name

### ISSUE THREAD

**Issue by yuchi** [sttts/ti-ignore-plugin#1]
It’s `.npmignore`, `.gitgnore`, `.jshintignore` and so on, **not** `.PRODUCT-ignore`.

What about `.tiignore`? It’s the double `i` that’s unpleasant? Why don‘t we go with `.titaniumignore`?

That said. Another great plugin/module/idea/tool! You’re on fire!

**Comment by sttts** [comment]
Pull request to support `.tiignore` as well is welcome ;-)

**Comment by yuchi** [comment]
Well, we can close this one :)
